import java.util.Scanner;
public class Programa6{
	public static void main(String[] args){
		Scanner l = new Scanner(System.in);
		String s = l.nextLine();
		char [] a = s.toCharArray();
		int i=0;
		while(i<a.length){
			switch (a[i]){
				case'a':a[i]='A';
					break;
				case'b':a[i]='B';
					break;
				case'c':a[i]='C';
					break;
				case'd':a[i]='D';
					break;
				case'e':a[i]='E';
					break;
				case'f':a[i]='F';
					break;
				case'g':a[i]='G';
					break;
				case'h':a[i]='H';
					break;
				case'i':a[i]='I';
					break;
				case'j':a[i]='J';
					break;
				case'k':a[i]='K';
					break;
				case'l':a[i]='L';
					break;
				case'm':a[i]='M';
					break;
				case'n':a[i]='N';
					break;
				case'o':a[i]='O';
					break;
				case'p':a[i]='P';
					break;
				case'q':a[i]='Q';
					break;
				case'r':a[i]='R';
					break;
				case's':a[i]='S';
					break;
				case't':a[i]='T';
					break;
				case'u':a[i]='U';
					break;
				case'v':a[i]='V';
					break;
				case'w':a[i]='W';
					break;
				case'x':a[i]='X';
					break;
				case'y':a[i]='Y';
					break;
				case'z':a[i]='Z';
					break;
			}
			i++;
		}
		i=0;
		while(i<a.length){
			System.out.print(a[i]);
			i++;
		}
		i=0;
		while(i<a.length){
			switch (a[i]){
				case'A':a[i]='a';
					break;
				case'B':a[i]='b';
					break;
				case'C':a[i]='c';
					break;
				case'D':a[i]='d';
					break;
				case'E':a[i]='e';
					break;
				case'F':a[i]='f';
					break;
				case'G':a[i]='g';
					break;
				case'H':a[i]='h';
					break;
				case'I':a[i]='i';
					break;
				case'J':a[i]='j';
					break;
				case'K':a[i]='k';
					break;
				case'L':a[i]='l';
					break;
				case'M':a[i]='m';
					break;
				case'N':a[i]='n';
					break;
				case'O':a[i]='o';
					break;
				case'P':a[i]='p';
					break;
				case'Q':a[i]='q';
					break;
				case'R':a[i]='r';
					break;
				case'S':a[i]='s';
					break;
				case'T':a[i]='t';
					break;
				case'U':a[i]='u';
					break;
				case'V':a[i]='v';
					break;
				case'W':a[i]='w';
					break;
				case'X':a[i]='x';
					break;
				case'Y':a[i]='y';
					break;
				case'Z':a[i]='z';
					break;
			}
			i++;
		}
		i=0;
	
			switch (a[0]){
				case'a':a[0]='A';
					break;
				case'b':a[0]='B';
					break;
				case'c':a[0]='C';
					break;
				case'd':a[0]='D';
					break;
				case'e':a[0]='E';
					break;
				case'f':a[0]='F';
					break;
				case'g':a[0]='G';
					break;
				case'h':a[0]='H';
					break;
				case'i':a[0]='I';
					break;
				case'j':a[0]='J';
					break;
				case'k':a[0]='K';
					break;
				case'l':a[0]='L';
					break;
				case'm':a[0]='M';
					break;
				case'n':a[0]='N';
					break;
				case'o':a[0]='O';
					break;
				case'p':a[0]='P';
					break;
				case'q':a[0]='Q';
					break;
				case'r':a[0]='R';
					break;
				case's':a[0]='S';
					break;
				case't':a[0]='T';
					break;
				case'u':a[0]='U';
					break;
				case'v':a[0]='V';
					break;
				case'w':a[0]='W';
					break;
				case'x':a[0]='X';
					break;
				case'y':a[0]='Y';
					break;
				case'z':a[0]='Z';
					break;
			}
		System.out.println("");
		while(i<a.length){
			System.out.print(a[i]);
			i++;
		}
		

	}
}
